baseURL = "https://lifetank.life/"
canonifyURLs = true
defaultContentLanguage = "en"
languageCode = "en-US"
paginate = 10
publishDir = "docs"
summaryLength = "10"
theme = "hello-friend-ng"
title = "Life Tank"
[languages.en]
copyright = "<a href=\"https://creativecommons.org/licenses/by-nc/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY-NC 4.0</a>"
keywords = ""
readOtherPosts = "Read other posts"
subtitle = "A simple theme for Hugo"
title = "Life Tank"
[languages.en.params.logo]
logoHomeLink = "/"
logoText = "Life Tank"
[[menu.main]]
identifier = "about"
name = "About"
url = "about/"
weight = 1
[[menu.main]]
identifier = "blog"
name = "Posts"
url = "/posts"
weight = 2
[params]
dateform = "Jan 2, 2006"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"
dateformShort = "Jan 2"
defaultTheme = "dark"
description = "My new homepage or blog"
disableReadOtherPosts = false
enableSharingButtons = true
homeSubtitle = "a blog about life and sensemaking"
images = [""]
keywords = "homepage, blog"
[[params.social]]
name = "github"
url = "https://github.com/kennethacurtis/lifetank"
[[params.social]]
name = "discord"
url = "https://discord.gg/rvZshvZRtj"
[taxonomies]
category = "blog"
series = "series"
tag = "tags"
