[build] 
  publish = "public"
  command = "hugo"
[build.environment]
  NODE_ENV = "production"
  HUGO_VERSION = "0.74.0" # if older, use format: 0.53 (no trailing zero)
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.branch-deploy]
  command = "hugo"
[context.branch-deploy.environment]
  NODE_ENV = "development"
  HUGO_VERSION = "0.74.0" # if older, use format: 0.53 (no trailing zero)
  HUGO_ENV = "development"
  HUGO_ENABLEGITINFO = "true"

[context.production]
  command = "hugo"
[context.production.environment]
  NODE_ENV = "production"
  HUGO_VERSION = "0.74.0" # if older, use format: 0.53 (no trailing zero)
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"